import mongoose from 'mongoose';

const studentProfileSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  collegeName: { type: String },
  degree: { type: String },
  major: { type: String },
  expectedGraduation: { type: Date },
  skills: [{ type: String }],
  githubUrl: { type: String },
  linkedinUrl: { type: String },
  resumeUrl: { type: String },
  professionalSummary: { type: String }, // Generated by AI
}, { timestamps: true });

export default mongoose.model('StudentProfile', studentProfileSchema);
